version: '2.4'
services:

  chatbot:
    build:
      context: ./chatbot
    image: chshin/chatbot:0.3
    depends_on:
      - cuda-9-0_cudnn-7-0
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - ./jupyter-config:/home/chshin/workspace/.jupyter
      - /data6:/home/chshin/workspace/data6
    runtime: nvidia
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    #command: jupyter notebook
  cuda-9-0_cudnn-7-0:
    image: encoredtechr/cuda:9.0-cudnn7.0
